processing:
  order:
  - retrieve
  - pattern_processor
  - ner_processor
  - llm_invoke
  - postprocessor
pattern_processor:
  custom_patterns:
    employee_id: \bEMP\d{6}\b
    account_number: \bACCT-\d{10}\b
    ip_address: \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b
    date_of_birth: \b(0[1-9]|1[0-2])/(0[1-9]|[12][0-9]|3[01])/\d{4}\b
ner_processor:
  model: en_core_web_sm
  entity_types: []
  sensitivity_levels: {}
llm_invoke:
  provider: openai
  model: gpt-4
  temperature: 0.3
  max_tokens: 1000
postprocessor:
  mode: restore_original
  additional_filtering: false
  placeholder_format: <redacted {entity_type}>
files:
  output_path: data/preprocessed_output.txt
  log_path: logs/pipeline.log
logging:
  enabled: true
  level: INFO
retriever:
  embeddings: openai
  retrieval_type: similarity_search
  k: 5
